import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
	title: "Contact | Hianatra",
	description: "Generated by create next app",
};

function ContactLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
	return children
}

export default ContactLayout