import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
	title: "Cours | Hianatra",
	description: "Generated by create next app",
};

function CoursesLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
	return (children)
}

export default CoursesLayout