import type { Metadata } from "next";
import "./globals.scss";
import Footer from "@/components/layout/Footer";
import NavBar from "@/components/layout/navBar";

export const metadata: Metadata = {
  title: "Hianatra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        <NavBar />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
