import React from "react";
import type { Metadata } from "next";
import "./globals.scss";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Accueil | Hianatra",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }: Readonly<{ children: React.ReactNode; params: Promise<{ locale: string }> }>) {
  const { locale } = await params
  return (
    <html lang={locale}>
      <body>
        <Providers locale={locale}>
          <Header />
          <main>
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
